{% set name = "georasters" %}
{% set version = "0.5.28" %}
{% set sha256 = "9da7d83171a64fec1941a1ec0a4746e38c18b4c3d497ab97afaa256b1376be16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python >=3.4
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - numpy
    - pandas
    - docopt
    - gdal
    - pyproj
    - scikit-image
    - matplotlib-base
    - coverage
    - fiona
    - geopandas
    - pysal
    - affine
    - rasterstats >=0.12

test:
  imports:
    - georasters
  requires:
    - coverage
    - pyshp >=1.1.4
    - pytest
    - pytest-cov >=2.2.0

about:
  home: http://github.com/ozak/georasters
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Tools for working with Geographical Information System Rasters

  description: |
    The GeoRasters package is a python module that provides
    a fast and flexible tool to work with GIS raster files.
    It provides the GeoRaster class, which makes working with
    rasters quite transparent and easy. In a way it tries to do
    for rasters what GeoPandas does for geometries.

    It includes tools to

    * Merge rasters
    * Plot rasters
    * Extract information from rasters
    * Given a point (lat,lon) find its location in a raster
    * Aggregate rasters to lower resolutions
    * Align two rasters of different sizes to common area and size
    * Get all the geographical information of raster
    * Create GeoTiff files easily
    * Load GeoTiff files as masked numpy rasters
    * Clip raster using geometries
    * Get zonal statistics using geometries
    * Spatial analysis tools

  doc_url: http://georasters.readthedocs.io/
  dev_url: https://github.com/ozak/georasters

extra:
  recipe-maintainers:
    - ozak
