travis:
  secure:
    BINSTAR_TOKEN: vjuvzUGNwjwHO6qHFXIT9cfxXLlSf8M51YYvdIF+ZVIzL8Fb8UT595D4lgUb6OhLm374scK71iW65GdTkWXQEzk200XZVPT4WDB1/Jmb724zDa3Pb+hFeZZmlppG7OCgx3VgwOP8AmumzcjS/nVkh5DyNQ3/2wY0PoTSkd3Vsh5VbiD+E156S09cIFqMXMajzNe+oOwsbA5kIpIBwogioBfDPeuL01520ooLqOw5lb7x1AJWA5Cxdd05xaPdSuu0xrIgbt2ywAqTrJyYLm4vEhAAvFrleRoV3m7h1HmeNy44Y31eGmwLMaJzWOsguu6xSpaq4zw4ajKBA2RzeO6cgnC0UANrmGLpsisuCuoigCcrRnXgpIyeUWk2zI7ORK8MWFoEodWG18kc6+60JarO56UL7/tdBX7FpzwuFcltYpC494f90ThIwkRAyvlJNUfpHMYeBEcdlbyZJmSJcQ2pszoslz82NoBvOsGtNRuz6QxrYhxFdLkUkeXV/eneK5JhFEDYR8S2eDPJIFAuKr16eeqsPjtmJXh8i1j2JdoEISQlzvavgzP5l6qZe4VxQx3biIvcewbEHS9ytonBORNyHPjVkjcs32MNIZ+Tal4UdSA/RxgbFLIo1GzC+uop4K5viPSe/3JGpDO4d/7fCTnXsSk0o6MMyYWYKR+U9ywn2R8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
