travis:
  secure:
    BINSTAR_TOKEN: fr2trF8BZX/NArkA4hjuFD06M4TbwcenozYIz3+Vy+vkRl+NWUbgWqD+ZMeu2iyIFk/Xerost3UIdtM+PadHQNViELW5wvmGqyXWfIwEu2tDN6OGNJrOY+sBS/on6/8EIS0AVHHxrm7QxOqLG+YZvAKsYDVXX+E6vr8b/D7xdL1hP5++9OUd9gELJc4kDlw1yZmjtzW1nF8BBwuGVDN+xcvY1cMDLv3A9HYSscevNi01f9lwyae2eqsR5IHaTeTLwpBc7cNx6VL5zeh/E+e0hpMVcuAEfeLYHimyoR41oAMVC+Oh+6zeHCQpIyE+0BfBAQ4J67JDsjZIswk/K0ufkzvf51zfOJao2S5tjszwCQYzm4Em3AgEAU89Kxg1sV9KSolVr8HhQ+a4PGPB9HOunks+8TM4h8BCrnqrNkT0yF8Rm9llIzG+FtxIiLAdLjolCeBrsnsnshpCNDJ7pcK0/3BiGUkdXjVrjW1ojYM2hjpDK7XjJ3dZ/5KJi5ym0kUaQgGHdqtYxoUh3JZf/mVv5Di4Cr/Dppfi5ralJHbp8P6La14m5cwKB/vu0Jgz/GmN5OkRgepTVFaOgargB00RXUXKal2SbBPe/IVqNIvS2nAzZDlQrY2likbfjXlocl59XT+ufdx4yfVKFsiSq3hWauQWl0Q8eaJFT+1mixeDxgs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
