travis:
  secure:
    BINSTAR_TOKEN: Fq8o+1McLHOFz4in/3QGGp0SGZX4w4xfk7puCM+UEao2VJimTpLWQvPWsAK3FrmKcLoph5JRBZf96kSKRnVf28qUbSvw+qIKF1RlQkTZBXAtEZLCZqxVlWlEgxQMd9YCLtg/KiwFZ3H8jxM+TVVUHu9nZvOesYqYNuz15m5FmhEzqN+mV4rVLe2toAKfLLfKoqU0gGmbIH8LmRZDq43HCrtFXsEunUF4epx/rTxXhv//iJQ2gamCXJVeGL6Kri/iM0vY+zABfZ/BRBU9vQhMgn6FQYZD7FITcbvPF3sA3cKAW55SvevmiGhpqluVJOVGdRDkZA329Cn2udzogt6M+3olY1Ls30Jqt7zylHLOXAon3qKY0Qeu6Ih1yhGQcugOjkTicWnWZmnOZEmvi+MnCb0ktCGjkTWd2/F0YCvwvciRA0QfafuzbNQJ1Kbz8zvv3KQK+orp3G8juh4HTiTmy8JlH5jww5icR3M19qnTU0aymrTaKOFdICvT0UAjjDUrLUnCCoJEM/jc4nU+eoscDMwBFDXuDzzPmes4wW+JUn2SSl6Kn1j4ueh4ySiM6hUh2K8Zu7zmJc8GiyhZ/RJ/lChcRhopQfKLZiyCORm9K6ViF17P/qHEwWSZN+2gr9rR/C/iI8D0Q0eaA+BHsj0rvP0fhBQkSeIoFXri0cWI6r0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
